# Generated by Django 5.0.3 on 2024-04-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_tag'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
